//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsMedicalCaseServiceEx
    {
        public int ID { get; set; }
        public int CaseID { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime ServiceStart { get; set; }
        public System.DateTime ServiceEnd { get; set; }
        public string N { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string Name { get; set; }
        public decimal Coverage { get; set; }
        public decimal RealPrice { get; set; }
        public decimal RealCustomerPaid { get; set; }
        public decimal OtherInsurantPaid { get; set; }
        public decimal DeductedAmount { get; set; }
        public Nullable<int> DeductionTypeID { get; set; }
        public decimal OurDiscountReal { get; set; }
        public decimal ToBePaidReal { get; set; }
        public Nullable<decimal> ToBePaidReal2 { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ClaimManagerID { get; set; }
        public Nullable<System.DateTime> ClaimManagerApproveDate { get; set; }
        public Nullable<int> HeadApproverID { get; set; }
        public Nullable<System.DateTime> HeadApproveDate { get; set; }
        public Nullable<int> AccountantID { get; set; }
        public Nullable<System.DateTime> AccountantApproveDate { get; set; }
        public string ExclusionComment { get; set; }
        public string PrescriptionFormN { get; set; }
        public Nullable<int> AppointmentServiceID { get; set; }
        public Nullable<int> GuaranteeLetterItemID { get; set; }
        public Nullable<int> ActID { get; set; }
        public Nullable<decimal> DeclaredEstimatedLoss { get; set; }
        public Nullable<int> NCSPID { get; set; }
        public Nullable<int> LabTestID { get; set; }
        public Nullable<int> NCSPID2 { get; set; }
        public Nullable<int> LabTestID2 { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> DeclarationServiceID { get; set; }
        public Nullable<bool> WasCreatedFromDeclaration { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> BedDays { get; set; }
        public Nullable<int> ToothNumber { get; set; }
        public Nullable<int> GuaranteeLetterDeclarationServiceID { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<int> MedicalClaimOperationID { get; set; }
        public Nullable<int> LastModifierID { get; set; }
        public Nullable<int> OriginalCaseServiceID { get; set; }
        public Nullable<bool> StateLimitExceeded { get; set; }
        public Nullable<bool> IsNotDefaultCoverage { get; set; }
        public Nullable<int> MedicalPlanCoverageID { get; set; }
    
        public virtual InsMedicalAppointmentService InsMedicalAppointmentService { get; set; }
        public virtual InsMedicalCaseEx InsMedicalCaseEx { get; set; }
    }
}
