//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsMedicalProviderInvoice
    {
        public InsMedicalProviderInvoice()
        {
            this.InsMedicalCaseExes = new HashSet<InsMedicalCaseEx>();
        }
    
        public int ID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int ProviderID { get; set; }
        public string N { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ServicePeriod { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<System.DateTime> OperatorChangeDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<int> ProgrammeTypeID { get; set; }
        public Nullable<int> InvoiceStatusID { get; set; }
        public Nullable<int> ServicePeriodYear { get; set; }
    
        public virtual ICollection<InsMedicalCaseEx> InsMedicalCaseExes { get; set; }
    }
}
