//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsMedicalAppointmentService
    {
        public InsMedicalAppointmentService()
        {
            this.InsMedicalCaseServiceExes = new HashSet<InsMedicalCaseServiceEx>();
        }
    
        public int ID { get; set; }
        public int AppointmentID { get; set; }
        public string PrescriptionFormN { get; set; }
        public string PrescriptionFormNByHand { get; set; }
        public int ProviderID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public int NumberOfUnits { get; set; }
        public string Service { get; set; }
        public decimal Coverage { get; set; }
        public decimal Price { get; set; }
        public decimal RequestedAmount { get; set; }
        public Nullable<System.DateTime> ServiceStart { get; set; }
        public Nullable<System.DateTime> ServiceEnd { get; set; }
        public string Comment { get; set; }
        public int StatusID { get; set; }
        public string AppointmentResult { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<bool> NonProviderAppointment { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> PrintFormTypeID { get; set; }
        public Nullable<int> NCSPID { get; set; }
        public Nullable<int> LabTestID { get; set; }
        public Nullable<int> NCSPID2 { get; set; }
        public Nullable<int> LabTestID2 { get; set; }
        public int PrintCount { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public Nullable<bool> AppointedASpecialist { get; set; }
        public Nullable<int> MedicinePriority { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> PaidByOther { get; set; }
        public Nullable<decimal> Deducted { get; set; }
        public Nullable<bool> StateLimitExceeded { get; set; }
        public Nullable<bool> IsNotDefaultCoverage { get; set; }
        public Nullable<int> MedicalPlanCoverageID { get; set; }
    
        public virtual InsMedicalAppointment InsMedicalAppointment { get; set; }
        public virtual ICollection<InsMedicalCaseServiceEx> InsMedicalCaseServiceExes { get; set; }
    }
}
