//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsMedicalAppointment
    {
        public InsMedicalAppointment()
        {
            this.InsMedicalAppointmentServices = new HashSet<InsMedicalAppointmentService>();
        }
    
        public int ID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> ApproverID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string N { get; set; }
        public string ManualN { get; set; }
        public int BranchID { get; set; }
        public int InsurantPolicyID { get; set; }
        public Nullable<bool> InsurantIsInsuredInOtherCompany { get; set; }
        public string InsurantOtherInsuranceCompany { get; set; }
        public Nullable<int> PatientPolicyID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public int Patient2InsurantRelationID { get; set; }
        public string Patient2InsurantRelation { get; set; }
        public Nullable<bool> PatientIsInsuredInOtherCompany { get; set; }
        public string PatientOtherInsuranceCompany { get; set; }
        public int DeclaratorID { get; set; }
        public int Declarator2PatientRelationID { get; set; }
        public string Declarator2PatientRelation { get; set; }
        public string Comment { get; set; }
        public string Cursus { get; set; }
        public Nullable<int> ICD10 { get; set; }
        public Nullable<int> FullDiagnosisID { get; set; }
        public string Diagnosis { get; set; }
        public string IlnessDescription { get; set; }
        public string Result { get; set; }
        public int StatusID { get; set; }
        public string ExclusionComment { get; set; }
        public Nullable<int> ProviderID { get; set; }
    
        public virtual ICollection<InsMedicalAppointmentService> InsMedicalAppointmentServices { get; set; }
    }
}
