//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsMedicalCaseEx
    {
        public InsMedicalCaseEx()
        {
            this.InsMedicalCaseServiceExes = new HashSet<InsMedicalCaseServiceEx>();
        }
    
        public int ID { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int CoordinatorID { get; set; }
        public Nullable<int> DeclarationID { get; set; }
        public int BranchID { get; set; }
        public string N { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public int DeclaratorID { get; set; }
        public int InsurantPolicyID { get; set; }
        public Nullable<int> PatientPolicyID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public int PaymentReceiverID { get; set; }
        public int PaymentTypeID { get; set; }
        public string Invoice { get; set; }
        public Nullable<bool> PatientIsInsuredInOtherCompany { get; set; }
        public string PatientOtherInsuranceCompany { get; set; }
        public Nullable<int> OtherInsuranceTypeID { get; set; }
        public Nullable<int> ICD10 { get; set; }
        public Nullable<int> FullDiagnosisID { get; set; }
        public string Diagnosis { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PaymentReceiverBankAccountID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> ICD10_2 { get; set; }
        public Nullable<int> ResponsiblePersonID { get; set; }
        public Nullable<System.DateTime> ResponsiblePersonChangeDate { get; set; }
        public Nullable<int> GuaranteeLetterDeclarationID { get; set; }
        public int VersionTypeID { get; set; }
        public Nullable<int> OriginalCaseID { get; set; }
        public System.Guid UID { get; set; }
    
        public virtual InsMedicalProviderInvoice InsMedicalProviderInvoice { get; set; }
        public virtual ICollection<InsMedicalCaseServiceEx> InsMedicalCaseServiceExes { get; set; }
    }
}
